# Custom Language File for Launcher Customizer

[ejs.app]
title = "CARTA"

[ejs.landing]
mediaGitHubURL = "https://github.com/CustomLauncherLab/CARTA"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"
mediaSoopURL = "#"
mediaChzzkURL = "#"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/CustomLauncherLab/CARTA"
supportLink = "https://github.com/CustomLauncherLab/CARTA/issues"

[ejs.welcome]
welcomeHeader = "CARTA"
welcomeDescription = ""
welcomeDescCTA = "계속하기 버튼을 눌러 계속 진행하여 주세요."